image: node:16-alpine
cache:
  paths:
     node_modules/

before_script:
   npm install

build:
  stage: build
  script:
     npm run build --configuration production --output-path=dist
  artifacts:
    paths:
       dist/

pages:
  stage: deploy
  script:
     mv dist public
  artifacts:
    paths:
    public
  only:
     main
