image: node:18

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build -- --configuration production
  artifacts:
    paths:
      - public/
pages:
  stage: deploy
  script:
     - echo "Deploying GitLab Pages"
  artifacts:
    paths:
      - public/
  only:
    - main
